### ISSUE TITLE
Installed map appears in 2.5.stable but not in pre-release 2.6.14732

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#12559]
The installed map "world_war_ii_v5_1942" - when clicking "Select Game" appears in 2.5.stable:
![stab](https://github.com/triplea-game/triplea/assets/20812775/126497a4-983c-4ae2-8e54-fd7c89d19a9e)

but not in 2.6.14732
![pre](https://github.com/triplea-game/triplea/assets/20812775/3de7a3ca-1e93-4b40-9e80-041841b95c31)

**Comment by TheDog-GH** [comment]
Its probably missing its map.yml at the map/description level

It should look like this

```
map_name: world_war_ii_v5_1942
games:
- game_name: WW2v5-Maintenance Costs
  file_name: WW2v5-Maintenance.xml
- game_name: WW2v5-Build Caps
  file_name: WW2v5-BuildCaps.xml
- game_name: WW2v5_1942_2nd_Edition_High_Production_Mod
  file_name: WW2v5_1942_2nd_Edition_High_Production_Mod.xml
```
