### ISSUE TITLE
ContentDownloader#<init>:78 - java.io.IOException

### ISSUE THREAD

**Issue by tripleabuilderbot** [triplea-game/triplea#13447]
## Log Message
Failed to download: https://github.com/triplea-maps/wwiinazithreat/tree/master/archive/master.zip

## TripleA Version
[2.7.14871](https://github.com/triplea-game/triplea/releases/tag/2.7.14871)

## Java Version
11.0.19

## Operating System
Windows 10

## Heap Size
4042M

## Stack Trace
```
Exception: java.io.IOException Unexpected status code (404)
java.lang.Exception
	at org.triplea.io.ContentDownloader.<init>(ContentDownloader.java:78)
	at org.triplea.io.ContentDownloader.<init>(ContentDownloader.java:56)
	at games.strategy.engine.framework.map.download.DownloadConfiguration.lambda$static$0(DownloadConfiguration.java:11)
	at games.strategy.engine.framework.map.download.ContentReader.downloadAndApplyAction(ContentReader.java:51)
	at games.strategy.engine.framework.map.download.ContentReader.downloadToFile(ContentReader.java:67)
	at games.strategy.engine.framework.map.download.DownloadFile.lambda$startAsyncDownload$2(DownloadFile.java:66)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

**Comment by frigoref** [comment]
@DanVanAtta It seems someone forgot to create the `archive/master.zip` file. What do you say we suggest a workflow to automatically create this file for repos under project [triplea-maps](https://github.com/triplea-maps)?
This way we avoid this specific `java.io.IOException`.

To have only one such workflow, I would suggest a new technical repo in which we put the following file `.github/workflows/archive-master.yml`:
```yml
name: Archive Master Branch

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create archive directory
        run: mkdir -p archive

      - name: Create master.zip
        run: git archive --format=zip --output=archive/master.zip HEAD

      - name: Commit and push master.zip
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add archive/master.zip
          git commit -m "Update master.zip archive" || echo "No changes to commit"
          git push origin ${{ inputs.branch }}
```
We then ask to create workflow file `.github/workflows/call-archive-master.yml` in each (non-technical) maps-repo
```yml
name: Call Archive Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-archive:
    uses: org/repo/.github/workflows/archive-master.yml@main
    with:
      branch: master
```
Would that work or do we have some special logic "for all triplea-maps" repos that would break then?
