### ISSUE TITLE
Empire Map remains on download list

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#1704]
When I download the Empire map from the Github repository, it remains in the list of maps to download.

**Comment by ssoloff** [comment]
Might have something to do with the version showing up as `null` for this map:

![empire](https://cloud.githubusercontent.com/assets/4826349/25978090/29fe24ce-368e-11e7-8b8e-4f123ad1beaf.png)

I'll take a look when I get a chance if someone else doesn't step in before then.

**Comment by ssoloff** [comment]
@RogerCooper This should be fixed when #1705 is merged.

Note that you'll have to reinstall Empire once that PR is merged in order to update your local map metadata.  After that, it should correctly appear in the Installed list.

Please advise if you're still having problems after the fix is available.

**Comment by ssoloff** [comment]
@RogerCooper The fix for this issue can be found in build [1.9.0.0.4241](https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.4241) or later.  Because only `triplea_maps.yaml` was changed, it should not be necessary for you to reinstall TripleA.  Your existing install should pick up the new YAML file automatically.

As I mentioned in my previous comment, you will need to reinstall the Empire map in order for it to correctly appear on the Installed tab.

**Comment by RogerCooper** [comment]
Same problem for New World Order Lebowski.

**Comment by ssoloff** [comment]
Yup, same problem for New World Order Lebowski.  Except, in this case, it looks like the `version` attribute is there, but it is in the wrong position, and is being applied to the previous record (which already has a `version` attribute):

```yaml
- mapName: Global War2
  mapCategory: EXPERIMENTAL
  url: https://github.com/triplea-maps/global_war2/archive/master.zip
  version: 1
  img: http://tripleamaps.sourceforge.net/images/TripleA_global_war_2_mini.png
  description: |
    <br>Global War 2
    <br>Created by Dagon81
    <br>
    <br>Filesize is huge, at 64mb, so it may take a while to download.  Now comes with relief tiles, thx dagon.
    <br>
    <br>Converted up to TripleA 1.2.x.x by Veqryn
  version: 1
- mapName: New World Order Lebowski Edition
  mapCategory: EXPERIMENTAL
  url: https://github.com/triplea-maps/new_world_order_lebowski_edition/archive/master.zip
  img: http://tripleamaps.sourceforge.net/images/TripleA_nwo_1939_lebowski_mini.png
  description: |
    <br>
    <br>A version of NWO by Lebowski.
    <br>Update by Ice
- mapName: WW2v3_11N
```

I'll modify the code to dump all maps with a `null` version and fix them all at once.
