### ISSUE TITLE
Add capability to launch Map Creator from within TripleA

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#1722]
Originally raised [here](https://github.com/triplea-maps/Project/issues/77#issuecomment-301993703):

> So for the map creator, I'd like to be able to launch it from TripleA. Essentially have a button probably on the main menu that would open it so its more integrated and obvious that we have map creation tools.

The Map Creator source is currently hosted in the `triplea-maps/Project` repo ([v1](https://github.com/triplea-maps/Project/tree/master/MapMakingTools/map_creator_v1), [v2](https://github.com/triplea-maps/Project/tree/master/MapMakingTools/map_creator_v2)).  However, there is currently no mechanism to build and release this tool in some form that can be easily downloaded by TripleA.  Implementing the feature described in this issue will probably require defining a mechanism for building and releasing Map Creator from that repo.

Note that `triplea_maps.yaml` currently contains an entry for a version of Map Creator that was built manually and hosted on SourceForge:

```yaml
- mapName: TripleA Map Creator
  url: http://downloads.sourceforge.net/project/tripleamaps/developer%20resources/map%20makers/TripleA_Map_Creator.zip
  version: 1
  mapType: MAP_TOOL
```

However, downloading this tool from the Download Maps window simply places the archive in the user's maps folder.  The user is then required to manually unpack the archive and launch the tool from outside TripleA.  The implementation of the feature described in this issue should not require any similar manual intervention on the part of the user (other than the initial download) to launch Map Creator.
