### ISSUE TITLE
Shall we set up an automated build of the shadow jar?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#214]
Related to #216, which is a check list of the steps that will be needed to complete this. To get a start, we need the bot account to be given appropriate access permissions.
 
--- 

To finish an automated release pipeline of the 'shadow jar', a release artifact we publish today, all that is needed from the admins is to grant write access to the 'shared bot' account 'tripleabuilderbot', I can modify the .travis.yml file to then finish the rest, and provide admins with the bot account credentials.

In this issue, I want to see if there are any questions/comments/concerns, and if there is agreement to the plan. If there is agreement to move forward, I'll create an issue with a checklist of the steps that would need to happen (not too many of them, but again, only one needed from admins). If there is agreement to the final checklist we can then move to executing on this phase of the build and release automation project.

For more context, the bot account needs write access to be able to push tags and to deploy artifacts to releases.  Otherwise the .travis.yml file will be updated to look really similar to the below (and note, this is the only file that will need to be modified, no updates to the gradle file, it already does the shadow jar build today):

#### Example of how .travis.yml will look
```
language: java
jdk:
- oraclejdk8
install: true
script:
- gradle zipMap
before_deploy:
- git config --global user.email "tripleabuilderbot@gmail.com"
- git config --global user.name "tripleabuilderbot"
- export MAP_TAGGED_VERSION="$MAP_VERSION.$TRAVIS_BUILD_NUMBER"
- git tag $MAP_TAGGED_VERSION -a -m "$MAP_TAGGED_VERSION"
- git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-maps/$REPO_NAME --tags
deploy:
  provider: releases
  api_key:
    secure: sTJxC1pAb5Q+hMTQAAr7BmdDHuUryGil+qgEr6rZkxmOPGqMQzsSemcwmzflR6+IWw6HQvcwJBUwXsItlhuHIGheolW9gKZY4mSc9LqH0z7xF/+YwG74h/2fv7EttQ19f5TLwF25AzgoSexbbuZcWPk4w/Qaewdg4s5qPkHpw8DXmIzjrIcZg+zIUoCJRDDidJ02AlXm4bgDI8upiD34ckjJMIO4z5tkiASvuADpxyqlBmcLinlNnq2gAOQt7gBbBOakz91bUSFxS0V+NtekZauRLel356EibCqe2VHb+PsZ1cblAJ5XhqSpz4NN8ZupRS/kxM0s3ZNP0imX4630cqqZnX20/ZoeADtiRwsau6FZj60uF3WQlqUM5ZzggRTW9oGjwCreaIjyvYbzBsEOrZKiT8vYPrUTufAHEH1LOJlFvKlwBy3Gm/Rk4CSllZ2dj88MNT3GtzdNmNK6IEqBjyZKtrmy9fUxaCihVDrNI2xpAXFDlZMpXrktbEIIL8oYgjl6wj+tWJHKMvhQxKnVRMZoJ9BOrh6rx4b+GYehXWS9/j+ZZl9gt6enE30rTn4K4UmtQ+8Jw1fb3Dx4cyLxw4ummS9nowAZGUx0J/8qasnyy50BxpdqLse9afZHivjqVnTk4kdqeDw2ClKZ9CO6hpf+AkIOefR0H5zxAzgsWX4=
  file: "$REPO_NAME.zip"
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    all_branches: true
```

This stack overflow gave steps for auto-pushing tags: http://stackoverflow.com/questions/28217556/travis-ci-auto-tag-build-for-github-release
